apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: govee2mqtt
  name: govee2mqtt
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: govee2mqtt
  template:
    metadata:
      labels:
        app: govee2mqtt
    spec:
      containers:
        - image: ghcr.io/wez/govee2mqtt:2025.11.25-60a39bcc # {"$imagepolicy": "homeassistant:govee2mqtt"}
          name: govee2mqtt
          env:
            - name: GOVEE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: govee2mqtt-secrets
                  key: password
            - name: GOVEE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: govee2mqtt-secrets
                  key: email
            - name: GOVEE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: govee2mqtt-secrets
                  key: apikey
            - name: GOVEE_MQTT_HOST
              value: mosquitto
            - name: GOVEE_TEMPERATURE_SCALE
              value: C
            - name: GOVEE_MQTT_PORT
              value: "1883"
            - name: TZ
              value: Europe/Berlin
          securityContext:
            privileged: true
