apiVersion: v1
data:
    email: ENC[AES256_GCM,data:MN6kdzjScXHfkIRTKj8mwc24C/O/okhMrySYlw==,iv:ClnCrZ9xv0xaftlqybF8y4edxRUaZ5TZ+lkq+J/lEBo=,tag:kytOMxbKNNcujmYfeQi1VA==,type:str]
    password: ENC[AES256_GCM,data:47BdhfWCIIqM8cdi6Tb+Vg==,iv:l1sNZlWFuJS5O7YLdQTyaxg3Z7dyHUndiTk63Isi9IE=,tag:JxKfdJzb70JqFQD4kkwWCA==,type:str]
    apikey: ENC[AES256_GCM,data:xnXHcn5vJ0U2KQFF5TPawoCEkYDyqHkrVas0aaK2UNFy0PMQDOHknH5Uty0VUIJw,iv:cnv8HI5+jFlensT8QkBT72ExQQ4NVjw6EiEOItTVX9Y=,tag:cW2QfEIDr4D1UgjOHV55vQ==,type:str]
kind: Secret
metadata:
    labels:
        app.kubernetes.io/name: govee2mqtt
        app.kubernetes.io/part-of: homeassistant
        kustomize.toolkit.fluxcd.io/name: homeassistant
        kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: govee2mqtt-secrets
    namespace: homeassistant
type: Opaque
sops:
    lastmodified: "2025-11-07T09:13:36Z"
    mac: ENC[AES256_GCM,data:Wy93RcuNRiQ50WIbl45aQGCcBYsUrpFTfR/XJPkuXLy8gVt7cGsfsUuDNxPz7GRDrZWCD35B5z4FXJGQKeAoSEBIT2W+02quBu1qUzMgZzQQB4Uv3Z3Wr8R0yLWk7Uqb00UcQSy8oRnTqt9n/+9+D+iToUDBYIqlg2ppYttt+UE=,iv:HrHhMzhX9OIpUIp20IIByOjcn7AesA7fRHwnaIOHJRk=,tag:G61rAhzgpPIIFr6Oaha88g==,type:str]
    pgp:
        - created_at: "2025-11-07T09:13:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz3gFPrah4NqAQ//UWN8BdGW3YAQV99/JO8AqbcVkAjALX7Dnx1TlD+l8cM5
            ECG1dEVFqU8yhs+icjViM8PkljwRqVPF18gV8Qx/Td7hLYsuFMztPyzfkzM2OIAf
            Lk94CHsqqN3zWPK+mgqJc0H580/4IhonJ1k8ZwHasjBQDmLHT21w3VEnagoKPxiS
            BSOc2qwFsJ8RZJRrJsYGo0BH7GbQwWN0diWsVoZr33V5vsfrZ9kWaxYp2X1adQI5
            2cFy0KxJMsUllFXseGG4QCRnb17Y06wcWz6T+zpfuoKnYJaHaP54bxt2rf2fcc/k
            WweLCcXmCeH2ZH1CE+iXUv24nzLQgZIQsdMzz960fCVdU9n1q6BMrvNP56A1tbVI
            cePya9v21d5ZQ1ojXWdg61uwOQTnUct08kHA9sVtWWQSYy6pn5HAO15gYLXu8FMg
            yA4CtBVvslCmumTqP67IlZf9qCuWS/1fk8/VNgM+N+6nQu87dnsc8CLwQ8qhwFmB
            WP6szWtJYD+wYnbghfqiZK3+KfzTkfMCuUY5apxoraYTt5zpZTbHalYX1JJjm2b7
            sJCqDLSi1ExRVqYRu/6/8Wfpkf9qii9mwSV+rv6NGwwNaqiwXQ0WU8+gcU2AmVXg
            92+W71uSOt4+hmlBvjL9cf4ijKeAsZz1Ith/GDy20BMSVEiAGbYVnGhR147KLXXS
            XgEcvM6Nl8kxfgjMh+A2QlfzEy+k32USnDdDBZpjHT2Sy0PVkZ+VkmSlmEYSiS6w
            Oq4lJdpWqCNxYAJy7B3Bk81iFLHl/M9VpFw46/2sbbFNLZDT64jx4jLZ3eHvu3w=
            =8mEd
            -----END PGP MESSAGE-----
          fp: A54D41469BEC6EAD68F0376C08957C67F1EF936E
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
